### ISSUE TITLE
训练自己的数据时checkpoint文件总是报错

### ISSUE THREAD

**Issue by ZacharySha** [csuhan/ReDet#102]
我下载了readme里面的权重文件，放在了对应的目录下。但是在run train.py时候会报错，如下：请问又大佬遇到过知道怎么解决吗？

ReResNet Orientation: 8	Fix Params: False
2021-09-22 18:24:55,564 - INFO - Distributed training: False
/opt/conda/conda-bld/pytorch_1573049310284/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1573049310284/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1573049310284/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
2021-09-22 18:25:30,098 - INFO - load model from: work_dirs/ReResNet_pretrain/re_resnet50_c8_batch256-12933bc2.pth
Traceback (most recent call last):
  File "tools/train.py", line 95, in <module>
    main()
  File "tools/train.py", line 73, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/liyi/shate/ReDet-master/mmdet/models/builder.py", line 60, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/liyi/shate/ReDet-master/mmdet/models/builder.py", line 32, in build
    return _build_module(cfg, registry, default_args)
  File "/home/liyi/shate/ReDet-master/mmdet/models/builder.py", line 24, in _build_module
    return obj_type(**args)
  File "/home/liyi/shate/ReDet-master/mmdet/models/detectors/ReDet.py", line 86, in __init__
    self.init_weights(pretrained=pretrained)
  File "/home/liyi/shate/ReDet-master/mmdet/models/detectors/ReDet.py", line 94, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/home/liyi/shate/ReDet-master/mmdet/models/backbones/re_resnet.py", line 698, in init_weights
    super(ReResNet, self).init_weights(pretrained)
  File "/home/liyi/shate/ReDet-master/mmdet/models/backbones/base_backbone.py", line 32, in init_weights
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/home/liyi/anaconda3/envs/redet/lib/python3.7/site-packages/mmcv-0.2.13-py3.7-linux-x86_64.egg/mmcv/runner/checkpoint.py", line 171, in load_checkpoint
    raise IOError('{} is not a checkpoint file'.format(filename))
OSError: work_dirs/ReResNet_pretrain/re_resnet50_c8_batch256-12933bc2.pth is not a checkpoint file

**Comment by csuhan** [comment]
> OSError: work_dirs/ReResNet_pretrain/re_resnet50_c8_batch256-12933bc2.pth is not a checkpoint file

猜测你下载的权重有问题，请检查是否可以使用`torch.load`加载
