### ISSUE TITLE
训练backbone遇到的问题

### ISSUE THREAD

**Issue by TheRealPoseidon** [csuhan/ReDet#114]
大佬您好，我尝试ReDet_mmcls分支时候遇到个问题，想向您请教

单GPU运行： python tools/train.py configs/re_resnet/re_resnet50_c8_batch256.py

得到这样的报错，可能是什么原因呢：

（省略了一些...）
2021-11-05 9:24:45,955 - mmcls - INFO - workflow: [('train', 1)], max: 100 epochs
2021-11-05 9:24:45,955 - mmcls - INFO - Checkpoints will be saved to /cluster/home/user4/main/sps/ReDet_mmcls/work_dirs/re_resnet50_c8_batch256 by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 157, in <module>
    main()
  File "tools/train.py", line 153, in main
    meta=meta)
  File "/cluster/home/user4/main/sps/ReDet_mmcls/mmcls/apis/train.py", line 117, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/cluster/home/user4/.conda/envs/redet_cls/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/cluster/home/user4/.conda/envs/redet_cls/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/cluster/home/user4/.conda/envs/redet_cls/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/cluster/home/user4/.conda/envs/redet_cls/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/cluster/home/user4/main/sps/ReDet_mmcls/mmcls/models/classifiers/base.py", line 136, in train_step
    losses = self(**data)
  File "/cluster/home/user4/.conda/envs/redet_cls/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/cluster/home/user4/main/sps/ReDet_mmcls/mmcls/models/classifiers/base.py", line 79, in forward
    return self.forward_train(img, **kwargs)
  File "/cluster/home/user4/main/sps/ReDet_mmcls/mmcls/models/classifiers/image.py", line 58, in forward_train
    loss = self.head.forward_train(x, gt_label)
  File "/cluster/home/user4/main/sps/ReDet_mmcls/mmcls/models/heads/linear_head.py", line 42, in forward_train
    losses = self.loss(cls_score, gt_label)
  File "/cluster/home/user4/main/sps/ReDet_mmcls/mmcls/models/heads/cls_head.py", line 37, in loss
    acc = self.compute_accuracy(cls_score, gt_label)
  File "/cluster/home/user4/.conda/envs/redet_cls/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/cluster/home/user4/main/sps/ReDet_mmcls/mmcls/models/losses/accuracy.py", line 62, in forward
    return accuracy(pred, target, self.topk)
  File "/cluster/home/user4/main/sps/ReDet_mmcls/mmcls/models/losses/accuracy.py", line 35, in accuracy
    correct_k = correct[:k].view(-1).float().sum(0, keepdim=True)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

**Comment by csuhan** [comment]
https://blog.csdn.net/flyfish1986/article/details/114410001
