### ISSUE TITLE
multiprocessing.pool.RemoteTraceback:

### ISSUE THREAD

**Issue by a1b2c3s4d4** [csuhan/ReDet#115]
(redet) linkdata@linkdata-PR4908P:~/yt/ReDet-master$ python DOTA_devkit/prepare_FAIR_other1103.py --srcpath /media/sdb/yt/dataset/FAIR_aug_all/  --dstpath /media/sdb/yt/dataset/redet1005/
padding: True
padding: True
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/linkdata/anaconda3/envs/redet/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/linkdata/anaconda3/envs/redet/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/linkdata/yt/ReDet-master/DOTA_devkit/SplitOnlyImage_multi_process.py", line 45, in SplitSingle
    assert np.shape(img) != ()
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "DOTA_devkit/prepare_FAIR_other1103.py", line 103, in <module>
    prepare(srcpath, dstpath)
  File "DOTA_devkit/prepare_FAIR_other1103.py", line 94, in prepare
    split_test.splitdata(1)
  File "/home/linkdata/yt/ReDet-master/DOTA_devkit/SplitOnlyImage_multi_process.py", line 85, in splitdata
    self.pool.map(worker, imagenames)
  File "/home/linkdata/anaconda3/envs/redet/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/linkdata/anaconda3/envs/redet/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AssertionError

在转数据集格式的时候出现了这个问题，请问是什么原因呀？

**Comment by csuhan** [comment]
参考多尺度数据生成：https://github.com/csuhan/ReDet/blob/master/DOTA_devkit/prepare_dota1_5_v2.py
config：https://github.com/csuhan/ReDet/blob/master/configs/ReDet/ReDet_re50_refpn_1x_dota15_ms.py
测试结束后的result merge：python tools/parse_results.py --config configs/ReDet/ReDet_re50_refpn_1x_dota15_ms.py --type OBB
