### ISSUE TITLE
Struct Error

### ISSUE THREAD

**Issue by Sairam13001** [csuhan/ReDet#130]
Hai sir, I am training ReDet on DOTA 1.5 and after 3 epochs, I am getting this error. I can't figure out why this problem is coming. 

Below is the Error lines:

Traceback (most recent call last):
  File "/home/ai20resch13001/envs/anaconda3/envs/redet/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
  File "/home/ai20resch13001/envs/anaconda3/envs/redet/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/ai20resch13001/envs/anaconda3/envs/redet/lib/python3.7/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

Could you kindly let me know how to solve this problem.

Thank you.

**Comment by csuhan** [comment]
please set `worker_per_gpu=0` in the config file
