### ISSUE TITLE
dota数据集结果解析

### ISSUE THREAD

**Issue by zhangcongzc** [csuhan/ReDet#132]
1. dota数据集在进行Task1_results_nms结果解析时报错，请问您知道怎么解决吗？
2. Task1_results指的是原图下的各个裁减子图之间结果直接加起来， 
Task1_results_nms则是要对原图内各框再进行一次nms, 不知道我理解的对吗？
希望得到您的解答！
Traceback (most recent call last):
  File "tools/parse_results.py", line 132, in <module>
    parse_results(config_file, pkl_file, output_path, type)
  File "tools/parse_results.py", line 104, in parse_results
    os.path.join(dstpath, 'Task1_results_nms'), nms_type=r'py_cpu_nms_poly_fast', o_thresh=current_thresh)
  File "/media/meng1/disk1/Zhangc/oriented_det/ReDet-master/DOTA_devkit/ResultMerge_multi_process.py", line 235, in mergebypoly_multiprocess
    py_cpu_nms_poly_fast, o_thresh)
  File "/media/meng1/disk1/Zhangc/oriented_det/ReDet-master/DOTA_devkit/ResultMerge_multi_process.py", line 213, in mergebase_parallel
    pool.map(mergesingle_fn, filelist)
  File "/home/meng1/anaconda3/envs/redet3.6/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/meng1/anaconda3/envs/redet3.6/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
IndexError: list index out of range

**Comment by csuhan** [comment]
建议检查Task1_results文件夹，查看是否存在空文件（即无检测结果）

**Comment by zhangcongzc** [comment]
> 建议检查Task1_results文件夹，查看是否存在空文件（即无检测结果）

检查发现Task1_results里15类的txt文件都非空，您看？

**Comment by csuhan** [comment]
可以对报错代码debug下：
https://github.com/csuhan/ReDet/blob/0b9addf3c2734659fd6ffc7824f2e659fde4419c/DOTA_devkit/ResultMerge_multi_process.py#L164

**Comment by zhangcongzc** [comment]
感谢！
