### ISSUE TITLE
训练自己数据集时报错，ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by lin0ww** [csuhan/ReDet#134]
能正常跑demo/demo_inference.py
数据集全是1024*1024，用DOTAdevkit里面的DOTA2COCO转化而来，可视化正常，json里的segmentation是旋转框，bbox是segmentation的最小外接矩形
配置文件由ReDet_re50_refpn_1x_dota15.py改了预训练模型路径、类别参数、数据集参数和学习率
Traceback (most recent call last):
  File "/home/zzx/Projects/PycharmProjects/Github/ReDet/tools/train.py", line 95, in <module>
    main()
  File "/home/zzx/Projects/PycharmProjects/Github/ReDet/tools/train.py", line 91, in main
    logger=logger)
  File "/home/zzx/Projects/PycharmProjects/Github/ReDet/mmdet/apis/train.py", line 61, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/zzx/Projects/PycharmProjects/Github/ReDet/mmdet/apis/train.py", line 197, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/zzx/software/anaconda3/envs/redet/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/zzx/software/anaconda3/envs/redet/lib/python3.7/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/zzx/Projects/PycharmProjects/Github/ReDet/mmdet/apis/train.py", line 39, in batch_processor
    losses = model(**data)
  File "/home/zzx/software/anaconda3/envs/redet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zzx/software/anaconda3/envs/redet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/zzx/software/anaconda3/envs/redet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zzx/Projects/PycharmProjects/Github/ReDet/mmdet/models/detectors/base_new.py", line 95, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/zzx/Projects/PycharmProjects/Github/ReDet/mmdet/models/detectors/ReDet.py", line 137, in forward_train
    gt_obbs = gt_mask_bp_obbs_list(gt_masks)
  File "/home/zzx/Projects/PycharmProjects/Github/ReDet/mmdet/core/bbox/transforms_rbbox.py", line 615, in gt_mask_bp_obbs_list
    return list(gt_obbs_list)
  File "/home/zzx/Projects/PycharmProjects/Github/ReDet/mmdet/core/bbox/transforms_rbbox.py", line 604, in gt_mask_bp_obbs
    gt_polys = mask2poly(gt_masks)
  File "/home/zzx/Projects/PycharmProjects/Github/ReDet/mmdet/core/bbox/transforms_rbbox.py", line 598, in mask2poly
    return list(polys)
  File "/home/zzx/Projects/PycharmProjects/Github/ReDet/mmdet/core/bbox/transforms_rbbox.py", line 584, in mask2poly_single
    max_contour = max(contours, key=len)
ValueError: max() arg is an empty sequence
求学长指点呀

**Comment by lin0ww** [comment]
是我蠢了，json里height和weight居然是512，改成1024之后就ok了
