### ISSUE TITLE
CUSTOM DATASET

### ISSUE THREAD

**Issue by Sairam13001** [csuhan/ReDet#140]
Hai sir, I am trying to train ReDet on VisDrone dataset. 

1. I converted VisDrone to COCO format
2. I created a file mmdet/datasets/VisDrone.py  and added the below code:
           from .coco import CocoDataset
            # And added the class information and all
3. In mmdet/datasets/__init__.py, I added the below:
    from .VisDrone import VisDroneDataset 
4. And added 'VisDroneDataset' to __all__ in mmdet/datasets/__init__.py
5. And created a config file for visdrone with necessary data paths set

When I run "python tools/train.py {config file of visdrone}, I get the error as given below:

Traceback (most recent call last):
  File "tools/train.py", line 95, in <module>
    main()
  File "tools/train.py", line 91, in main
    logger=logger)
  File "/home/ai20resch13001/ReDet-base/mmdet/apis/train.py", line 61, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/ai20resch13001/ReDet-base/mmdet/apis/train.py", line 197, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/DATA/ai20resch13001/anaconda3/envs/redet-base/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/DATA/ai20resch13001/anaconda3/envs/redet-base/lib/python3.7/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/ai20resch13001/ReDet-base/mmdet/apis/train.py", line 39, in batch_processor
    losses = model(**data)
  File "/DATA/ai20resch13001/anaconda3/envs/redet-base/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/DATA/ai20resch13001/anaconda3/envs/redet-base/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/DATA/ai20resch13001/anaconda3/envs/redet-base/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/DATA/ai20resch13001/anaconda3/envs/redet-base/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/DATA/ai20resch13001/anaconda3/envs/redet-base/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/DATA/ai20resch13001/anaconda3/envs/redet-base/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ai20resch13001/ReDet-base/mmdet/models/detectors/base_new.py", line 95, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/ai20resch13001/ReDet-base/mmdet/models/detectors/ReDet.py", line 136, in forward_train
    gt_obbs = gt_mask_bp_obbs_list(gt_masks)
  File "/home/ai20resch13001/ReDet-base/mmdet/core/bbox/transforms_rbbox.py", line 597, in gt_mask_bp_obbs_list
    return list(gt_obbs_list)
  File "/home/ai20resch13001/ReDet-base/mmdet/core/bbox/transforms_rbbox.py", line 587, in gt_mask_bp_obbs
    gt_polys = mask2poly(gt_masks)
  File "/home/ai20resch13001/ReDet-base/mmdet/core/bbox/transforms_rbbox.py", line 582, in mask2poly
    return list(polys)
  File "/home/ai20resch13001/ReDet-base/mmdet/core/bbox/transforms_rbbox.py", line 569, in mask2poly_single
    max_contour = max(contours, key=len)
ValueError: max() arg is an empty sequence

I took the config file of DOTA and modified the data path to VisDrone paths. Should I modify anything else like img_scale??

Could you kindly let me know how to overcome this error.

**Comment by csuhan** [comment]
You need to filter out small instances to make sure the `cv2.findContours` work.
Try to filter out samll object in your dataset, or set `checkmask=True`:
https://github.com/csuhan/ReDet/blob/0b9addf3c2734659fd6ffc7824f2e659fde4419c/mmdet/datasets/custom.py?#L297-L308
