### ISSUE TITLE
ninja: error: build.ninja:3: lexing error

### ISSUE THREAD

**Issue by yuan-kai-design** [csuhan/ReDet#171]
ase\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: error: build.ninja:3: lexing error

Traceback (most recent call last):
  File "E:\anaconda3_python38\envs\mmdet\lib\site-packages\torch\utils\cpp_extension.py", line 1667, in _run_ninja_build
    subprocess.run(
  File "E:\anaconda3_python38\envs\mmdet\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
I want to know how to solve this problem

**Comment by meixiangzhang** [comment]
I have encountered the same problem. Have you resolved it? How did it solve it? Thank you!
