### ISSUE TITLE
ModuleNotFoundError: No module named 'ipykernel'

### ISSUE THREAD

**Issue by chandlerbing65nm** [csuhan/ReDet#18]
I tried testing your model but I got error, can you help me with this? 

This is what error I got.

`!python tools/test.py configs/ReDet/ReDet_re50_refpn_1x_dota15.py work_dirs/ReDet_re50_refpn_1x_dota15/ReDet_re50_refpn_1x_dota15-7f2d6dda.pth --out work_dirs/ReDet_re50_refpn_1x_dota15/results.pkl`

`Traceback (most recent call last):
  File "tools/test.py", line 12, in <module>
    from mmdet.apis import init_dist
  File "/content/ReDet/mmdet/apis/__init__.py", line 2, in <module>
    from .train import train_detector
  File "/content/ReDet/mmdet/apis/train.py", line 10, in <module>
    from mmdet import datasets
  File "/content/ReDet/mmdet/datasets/__init__.py", line 1, in <module>
    from .DOTA import DOTADataset, DOTADataset_v3
  File "/content/ReDet/mmdet/datasets/DOTA.py", line 1, in <module>
    from .coco import CocoDataset
  File "/content/ReDet/mmdet/datasets/coco.py", line 2, in <module>
    from pycocotools.coco import COCO
  File "/usr/local/lib/python3.7/site-packages/pycocotools-2.0.2-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 49, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.7/site-packages/matplotlib-3.4.2-py3.7-linux-x86_64.egg/matplotlib/pyplot.py", line 2500, in <module>
    switch_backend(rcParams["backend"])
  File "/usr/local/lib/python3.7/site-packages/matplotlib-3.4.2-py3.7-linux-x86_64.egg/matplotlib/pyplot.py", line 277, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "/usr/local/lib/python3.7/site-packages/matplotlib-3.4.2-py3.7-linux-x86_64.egg/matplotlib/pyplot.py", line 278, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'ipykernel'`

**Comment by csuhan** [comment]
we have not tested on colab.
You can try `pip install jupyter` or `pip install ipykernel`.

Please note our repo requires torch<=1.3 (it may be hard to install on colab via pip).

**Comment by chandlerbing65nm** [comment]
> we have not tested on colab.
> You can try `pip install jupyter` or `pip install ipykernel`.
> 
> Please note our repo requires torch<=1.3 (it may be hard to install on colab via pip).

also, What version of Python did you use? I encountered problems when using version 3.6 and 3.8.

**Comment by csuhan** [comment]
Please refer to https://github.com/csuhan/ReDet/blob/master/INSTALL.md for data preparation

**Comment by csuhan** [comment]
Yeah, the reason is our inference code tries to get the `classname` tuple with the function `get_dataset`, while `get_dataset` requires annotation files:
```
FileNotFoundError: [Errno 2] No such file or directory: '/workfs/jmhan/dota15_1024_ms/test1024/DOTA1_5_test1024.json
```
To temporarily solve the issue, 
https://github.com/csuhan/ReDet/blob/44825e60a9ac7adc2aa84783982f1955fdf9740e/demo_large_image.py#L89-L90

Try to **replace** the two lines above with
```
# for DOTA v1.0
self.classnames = ('plane', 'baseball-diamond',
                'bridge', 'ground-track-field',
                'small-vehicle', 'large-vehicle',
                'ship', 'tennis-court',
                'basketball-court', 'storage-tank',
                'soccer-ball-field', 'roundabout',
                'harbor', 'swimming-pool',
                'helicopter')
```

**Comment by chandlerbing65nm** [comment]
@csuhan Thanks for the help. Sorry to bother, but I still got the same error. 

my colab can be run directly here: `https://colab.research.google.com/drive/1MARFKSAUTHUu4lA7eYLA0TLrQZm9WOZF?usp=sharing` can you try running it in your colab to see if the same error persist?

**Comment by chandlerbing65nm** [comment]
> I know the problem....
> 
> If you want to test the performance on DOTA, you must **download** and **prepare** the dataset. https://github.com/csuhan/ReDet/blob/master/GETTING_STARTED.md
> 
> While the modifications to `demo_large_image.py` is just for inference on a single image.

Yup, that's what I'm thinking too. It's just that the DOTA dataset is filesize. I'll try to download it. Thanks for the help btw.
