### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by chandlerbing65nm** [csuhan/ReDet#19]
Hello, I have now processed the DOTA dataset and obtained the `.json` files. But I got this error:

```
!python tools/test.py configs/ReDet/ReDet_re50_refpn_1x_dota15.py work_dirs/ReDet_re50_refpn_1x_dota15/ReDet_re50_refpn_1x_dota15-7f2d6dda.pth --out work_dirs/ReDet_re50_refpn_1x_dota15/results.pkl 
```

```
ReResNet Orientation: 8	Fix Params: False
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
/opt/conda/conda-bld/pytorch_1573049310284/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1573049310284/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1573049310284/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
Traceback (most recent call last):
  File "tools/test.py", line 208, in <module>
    main()
  File "tools/test.py", line 168, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location='cpu')
  File "/usr/local/lib/python3.7/site-packages/mmcv-0.2.13-py3.7-linux-x86_64.egg/mmcv/runner/checkpoint.py", line 172, in load_checkpoint
    checkpoint = torch.load(filename, map_location=map_location)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 603, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

My data directory is in:

```
./ReDet/data
          ---dota15
                --train
                --val
                --test
          ---dota15_1024
                --test1024
                --trainval1024
```

**Comment by chandlerbing65nm** [comment]
I tried using DOTA_v1.0 dataset, same error occurs.

**Comment by chandlerbing65nm** [comment]
Now, when I try to run the demo_large_image.py, I again get this issue.

```
!python demo_large_image.py
```

```
ReResNet Orientation: 8	Fix Params: False
/opt/conda/conda-bld/pytorch_1573049310284/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1573049310284/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/opt/conda/conda-bld/pytorch_1573049310284/work/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
Traceback (most recent call last):
  File "demo_large_image.py", line 143, in <module>
    r"work_dirs/ReDet_re50_refpn_1x_dota1/ReDet_re50_refpn_1x_dota1-a025e6b1.pth")
  File "demo_large_image.py", line 97, in __init__
    self.model = init_detector(config_file, checkpoint_file, device='cuda:0')
  File "/content/ReDet/mmdet/apis/inference.py", line 35, in init_detector
    checkpoint = load_checkpoint(model, checkpoint)
  File "/usr/local/lib/python3.7/site-packages/mmcv-0.2.13-py3.7-linux-x86_64.egg/mmcv/runner/checkpoint.py", line 172, in load_checkpoint
    checkpoint = torch.load(filename, map_location=map_location)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 603, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

**Comment by chandlerbing65nm** [comment]
Solution: model files are corrupted when pushed to github. Used gdrive for saving of the model files.
