### ISSUE TITLE
自定义数据集

### ISSUE THREAD

**Issue by zhangvia** [csuhan/ReDet#27]
学长你好，我想自定义一个数据集来跑这个模型，我把数据集的标注转成了coco格式如下所示。然后修改了config文件的数据集路径，为什么还是会报错。错误如下：
"images":[],
"categories":[],
"annotations":[
{
"area":2054.1579212663173,
"category_id":4,
"segmentation":"polygon",
"iscrowd":0,
"bbox":[
645.6300334536613,
304.6851641094081,
24.166563779603734,
85
],
"image_id":1,
"id":1
},

Traceback (most recent call last):
  File "tools/train.py", line 95, in <module>
    main()
  File "tools/train.py", line 91, in main
    logger=logger)
  File "/home/localchao/LHX/jyz/ReDet/mmdet/apis/train.py", line 61, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/localchao/LHX/jyz/ReDet/mmdet/apis/train.py", line 197, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/localchao/anaconda3/envs/CG-Net/lib/python3.7/site-packages/mmcv-0.2.13-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/localchao/anaconda3/envs/CG-Net/lib/python3.7/site-packages/mmcv-0.2.13-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 260, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/localchao/anaconda3/envs/CG-Net/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/localchao/anaconda3/envs/CG-Net/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/localchao/anaconda3/envs/CG-Net/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/localchao/anaconda3/envs/CG-Net/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/localchao/anaconda3/envs/CG-Net/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/localchao/anaconda3/envs/CG-Net/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/localchao/LHX/jyz/ReDet/mmdet/datasets/custom.py", line 191, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/localchao/LHX/jyz/ReDet/mmdet/datasets/custom.py", line 229, in prepare_train_img
    ann = self.get_ann_info(idx)
  File "/home/localchao/LHX/jyz/ReDet/mmdet/datasets/coco.py", line 43, in get_ann_info
    return self._parse_ann_info(ann_info, self.with_mask)
  File "/home/localchao/LHX/jyz/ReDet/mmdet/datasets/coco.py", line 91, in _parse_ann_info
    gt_masks.append(self.coco.annToMask(ann))
  File "/home/localchao/anaconda3/envs/CG-Net/lib/python3.7/site-packages/pycocotools-2.0.2-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 441, in annToMask
    rle = self.annToRLE(ann)
  File "/home/localchao/anaconda3/envs/CG-Net/lib/python3.7/site-packages/pycocotools-2.0.2-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 428, in annToRLE
    elif type(segm['counts']) == list:
TypeError: string indices must be integers

**Comment by zhangvia** [comment]
另外，学长能否给个邮箱，交流方便一点
