### ISSUE TITLE
KeyError: 'ReDet is not in the models registry'

### ISSUE THREAD

**Issue by SamMohel** [csuhan/ReDet#37]
i tried to train datasets but got 
`Traceback (most recent call last):
  File "train.py", line 95, in <module>
    main()
  File "train.py", line 73, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/path/mmdetection/mmdet/models/builder.py", line 58, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/usr/local/lib/python3.6/dist-packages/mmcv/utils/registry.py", line 210, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/cnn/builder.py", line 26, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'ReDet is not in the models registry'`

**Comment by csuhan** [comment]
Make sure you have installed `ReDet`
the code path should be `/path/ReDet` rather than `/path/mmdetection`

**Comment by SamMohel** [comment]
yes you are right .. the problem with me was in installing ReDet
