### ISSUE TITLE
RuntimeError: all tensors must be on devices[0]

### ISSUE THREAD

**Issue by TangLinJie** [csuhan/ReDet#45]
I have followed the Install.md file as given. There is not any error in the Install procedure. But when I run 'CUDA_VISIBLE_DEVICES=0,1,2,3 ./tools/dist_train.sh configs/ReDet/ReDet_re50_refpn_1x_mydataset.py 4 --validate', I get the following error, 

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
ReResNet Orientation: 8 Fix Params: False
ReResNet Orientation: 8 Fix Params: False
ReResNet Orientation: 8 Fix Params: False
ReResNet Orientation: 8 Fix Params: False
/tmp/pip-req-build-4baxydiv/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/tmp/pip-req-build-4baxydiv/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/tmp/pip-req-build-4baxydiv/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/tmp/pip-req-build-4baxydiv/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/tmp/pip-req-build-4baxydiv/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/tmp/pip-req-build-4baxydiv/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
2021-07-07 20:19:27,048 - INFO - Distributed training: True
/tmp/pip-req-build-4baxydiv/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/tmp/pip-req-build-4baxydiv/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/tmp/pip-req-build-4baxydiv/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/tmp/pip-req-build-4baxydiv/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/tmp/pip-req-build-4baxydiv/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/tmp/pip-req-build-4baxydiv/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
loading annotations into memory...
Done (t=0.06s)
creating index...
index created!
loading annotations into memory...
Done (t=0.06s)
creating index...
index created!
2021-07-07 20:20:58,958 - INFO - load model from: work_dirs/ReResNet_pretrain/re_resnet50_c8_batch256-25b16846.pth
2021-07-07 20:20:59,018 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: head.fc.weight, head.fc.bias

missing keys in source state_dict: conv1.filter, layer1.0.conv1.filter, layer1.0.conv2.filter, layer1.0.conv3.filter, layer1.0.downsample.0.filter, layer1.1.conv1.filter, layer1.1.conv2.filter, layer1.1.conv3.filter, layer1.2.conv1.filter, layer1.2.conv2.filter, layer1.2.conv3.filter, layer2.0.conv1.filter, layer2.0.conv2.filter, layer2.0.conv3.filter, layer2.0.downsample.0.filter, layer2.1.conv1.filter, layer2.1.conv2.filter, layer2.1.conv3.filter, layer2.2.conv1.filter, layer2.2.conv2.filter, layer2.2.conv3.filter, layer2.3.conv1.filter, layer2.3.conv2.filter, layer2.3.conv3.filter, layer3.0.conv1.filter, layer3.0.conv2.filter, layer3.0.conv3.filter, layer3.0.downsample.0.filter, layer3.1.conv1.filter, layer3.1.conv2.filter, layer3.1.conv3.filter, layer3.2.conv1.filter, layer3.2.conv2.filter, layer3.2.conv3.filter, layer3.3.conv1.filter, layer3.3.conv2.filter, layer3.3.conv3.filter, layer3.4.conv1.filter, layer3.4.conv2.filter, layer3.4.conv3.filter, layer3.5.conv1.filter, layer3.5.conv2.filter, layer3.5.conv3.filter, layer4.0.conv1.filter, layer4.0.conv2.filter, layer4.0.conv3.filter, layer4.0.downsample.0.filter, layer4.1.conv1.filter, layer4.1.conv2.filter, layer4.1.conv3.filter, layer4.2.conv1.filter, layer4.2.conv2.filter, layer4.2.conv3.filter

loading annotations into memory...
loading annotations into memory...
Done (t=0.07s)
creating index...
index created!
Done (t=0.07s)
creating index...
index created!
Traceback (most recent call last):
  File "./tools/train.py", line 95, in <module>
    main()
  File "./tools/train.py", line 91, in main
    logger=logger)
  File "/home/ljtang/ReDet/mmdet/apis/train.py", line 59, in train_detector
Traceback (most recent call last):
  File "./tools/train.py", line 95, in <module>
    _dist_train(model, dataset, cfg, validate=validate)
  File "/home/ljtang/ReDet/mmdet/apis/train.py", line 144, in _dist_train
Traceback (most recent call last):
  File "./tools/train.py", line 95, in <module>
    model = MMDistributedDataParallel(model.cuda())
  File "/home/ljtang/miniconda3/envs/dbpp/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 300, in __init__
    main()
  File "./tools/train.py", line 91, in main
        main()logger=logger)

  File "/home/ljtang/ReDet/mmdet/apis/train.py", line 59, in train_detector
  File "./tools/train.py", line 91, in main
    self._ddp_init_helper()
  File "/home/ljtang/miniconda3/envs/dbpp/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 318, in _ddp_init_helper
    _dist_train(model, dataset, cfg, validate=validate)    
logger=logger)
  File "/home/ljtang/ReDet/mmdet/apis/train.py", line 144, in _dist_train
  File "/home/ljtang/ReDet/mmdet/apis/train.py", line 59, in train_detector
    self._module_copies = replicate(self.module, self.device_ids, detach=True)
      File "/home/ljtang/miniconda3/envs/dbpp/lib/python3.7/site-packages/torch/nn/parallel/replicate.py", line 96, in replicate
_dist_train(model, dataset, cfg, validate=validate)
  File "/home/ljtang/ReDet/mmdet/apis/train.py", line 144, in _dist_train
    model = MMDistributedDataParallel(model.cuda())
  File "/home/ljtang/miniconda3/envs/dbpp/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 300, in __init__
    param_copies = _broadcast_coalesced_reshape(params, devices, detach)
  File "/home/ljtang/miniconda3/envs/dbpp/lib/python3.7/site-packages/torch/nn/parallel/replicate.py", line 75, in _broadcast_coalesced_reshape
    model = MMDistributedDataParallel(model.cuda())
  File "/home/ljtang/miniconda3/envs/dbpp/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 300, in __init__
    self._ddp_init_helper()
      File "/home/ljtang/miniconda3/envs/dbpp/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 318, in _ddp_init_helper
return comm.broadcast_coalesced(tensors, devices)
  File "/home/ljtang/miniconda3/envs/dbpp/lib/python3.7/site-packages/torch/cuda/comm.py", line 39, in broadcast_coalesced
    self._ddp_init_helper()
  File "/home/ljtang/miniconda3/envs/dbpp/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 318, in _ddp_init_helper
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: all tensors must be on devices[0]
    self._module_copies = replicate(self.module, self.device_ids, detach=True)
  File "/home/ljtang/miniconda3/envs/dbpp/lib/python3.7/site-packages/torch/nn/parallel/replicate.py", line 96, in replicate
    self._module_copies = replicate(self.module, self.device_ids, detach=True)    
param_copies = _broadcast_coalesced_reshape(params, devices, detach)
  File "/home/ljtang/miniconda3/envs/dbpp/lib/python3.7/site-packages/torch/nn/parallel/replicate.py", line 96, in replicate
  File "/home/ljtang/miniconda3/envs/dbpp/lib/python3.7/site-packages/torch/nn/parallel/replicate.py", line 75, in _broadcast_coalesced_reshape
        return comm.broadcast_coalesced(tensors, devices)param_copies = _broadcast_coalesced_reshape(params, devices, detach)

  File "/home/ljtang/miniconda3/envs/dbpp/lib/python3.7/site-packages/torch/cuda/comm.py", line 39, in broadcast_coalesced
  File "/home/ljtang/miniconda3/envs/dbpp/lib/python3.7/site-packages/torch/nn/parallel/replicate.py", line 75, in _broadcast_coalesced_reshape
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
    return comm.broadcast_coalesced(tensors, devices)
RuntimeError:   File "/home/ljtang/miniconda3/envs/dbpp/lib/python3.7/site-packages/torch/cuda/comm.py", line 39, in broadcast_coalesced
all tensors must be on devices[0]
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: all tensors must be on devices[0]

**Comment by fmy7834** [comment]
How do you solve it? I meet the same problem.
