### ISSUE TITLE
Has anyone been successful for cuda 11.0?

### ISSUE THREAD

**Issue by colsona** [csuhan/ReDet#55]
I have tried it in cuda 11.0 torch1.9.0 but there are so many problems for it.

**Comment by csuhan** [comment]
Please paste the log

**Comment by colsona** [comment]
> Please paste the log

when I run prepare_dota1_5, it has issues like:
`multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/Anaconda3/envs/redet/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/Anaconda3/envs/redet/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/data1/lengyihong/code/code/copy/ReDet/DOTA_devkit/SplitOnlyImage_multi_process.py", line 45, in SplitSingle
    assert np.shape(img) != ()
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/data1/lengyihong/code/code/copy/ReDet/DOTA_devkit/prepare_dota1_5.py", line 101, in <module>
    prepare(srcpath, dstpath)
  File "/home/data1/lengyihong/code/code/copy/ReDet/DOTA_devkit/prepare_dota1_5.py", line 92, in prepare
    split_test.splitdata(1)
  File "/home/data1/lengyihong/code/code/copy/ReDet/DOTA_devkit/SplitOnlyImage_multi_process.py", line 85, in splitdata
    self.pool.map(worker, imagenames)
  File "/opt/Anaconda3/envs/redet/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/Anaconda3/envs/redet/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AssertionError`

**Comment by colsona** [comment]
> Please paste the log

When I use cuda 110, it will meet some issues , especially mmcv(can't run bash compile.sh). I try solutions in github, but it can't work, now I am trying cuda 10.0.

**Comment by colsona** [comment]
> > Please paste the log
> 
> when I run prepare_dota1_5, it has issues like:
> `multiprocessing.pool.RemoteTraceback:
> """
> Traceback (most recent call last):
> File "/opt/Anaconda3/envs/redet/lib/python3.7/multiprocessing/pool.py", line 121, in worker
> result = (True, func(*args, **kwds))
> File "/opt/Anaconda3/envs/redet/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
> return list(map(*args))
> File "/home/data1/lengyihong/code/code/copy/ReDet/DOTA_devkit/SplitOnlyImage_multi_process.py", line 45, in SplitSingle
> assert np.shape(img) != ()
> AssertionError
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "/home/data1/lengyihong/code/code/copy/ReDet/DOTA_devkit/prepare_dota1_5.py", line 101, in
> prepare(srcpath, dstpath)
> File "/home/data1/lengyihong/code/code/copy/ReDet/DOTA_devkit/prepare_dota1_5.py", line 92, in prepare
> split_test.splitdata(1)
> File "/home/data1/lengyihong/code/code/copy/ReDet/DOTA_devkit/SplitOnlyImage_multi_process.py", line 85, in splitdata
> self.pool.map(worker, imagenames)
> File "/opt/Anaconda3/envs/redet/lib/python3.7/multiprocessing/pool.py", line 268, in map
> return self._map_async(func, iterable, mapstar, chunksize).get()
> File "/opt/Anaconda3/envs/redet/lib/python3.7/multiprocessing/pool.py", line 657, in get
> raise self._value
> AssertionError`

It causes by wrong datasets.
