### ISSUE TITLE
RuntimeError: cuda runtime error (701) : too many resources requested for launch at src/riroi_align_kernel.cu:389

### ISSUE THREAD

**Issue by 1994su** [csuhan/ReDet#64]

**Comment by 1994su** [comment]
home/cresda/ProgramCode/ReDet-master_cuda/mmdet/core/anchor/anchor_target.py:112: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at  /pytorch/aten/src/ATen/native/IndexingUtils.h:20.)
  anchors = flat_anchors[inside_flags, :]
/home/cresda/ProgramCode/ReDet-master_cuda/mmdet/core/bbox/samplers/random_sampler.py:37: UserWarning: This overload of nonzero is deprecated:
	nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
	nonzero(Tensor input, *, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  pos_inds = torch.nonzero(assign_result.gt_inds > 0)
/home/cresda/ProgramCode/ReDet-master_cuda/mmdet/core/anchor/anchor_target.py:185: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at  /pytorch/aten/src/ATen/native/IndexingUtils.h:20.)
  ret[inds] = data
/home/cresda/ProgramCode/ReDet-master_cuda/mmdet/core/anchor/anchor_target.py:189: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at  /pytorch/aten/src/ATen/native/IndexingUtils.h:20.)
  ret[inds, :] = data
/home/cresda/ProgramCode/ReDet-master_cuda/mmdet/models/rbbox_heads/rbbox_head.py:314: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at  /pytorch/aten/src/ATen/native/IndexingUtils.h:20.)
  bboxes_list.append(bboxes[keep_inds])
THCudaCheck FAIL file=src/riroi_align_kernel.cu line=389 error=701 : too many resources requested for launch
Traceback (most recent call last):
  File "tools/train.py", line 95, in <module>
    main()
  File "tools/train.py", line 91, in main
    logger=logger)
  File "/home/cresda/ProgramCode/ReDet-master_cuda/mmdet/apis/train.py", line 61, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/cresda/ProgramCode/ReDet-master_cuda/mmdet/apis/train.py", line 197, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/cresda/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/cresda/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 271, in train
    self.call_hook('after_train_iter')
  File "/home/cresda/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 229, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/cresda/anaconda3/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 17, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/cresda/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/cresda/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuda runtime error (701) : too many resources requested for launch at src/riroi_align_kernel.cu:389

**Comment by csuhan** [comment]
https://github.com/csuhan/ReDet/issues/4
