### ISSUE TITLE
HRSC2016 testing

### ISSUE THREAD

**Issue by mmoghadam11** [csuhan/ReDet#82]
it needs test.txt for eval
how can i make it??

**Comment by csuhan** [comment]
Note train.txt and test.txt in HRSC2016 are .txt files recording image names without extension.

For example:
```
P00001
P00002
...
```

**Comment by mmoghadam11** [comment]
> Note train.txt and test.txt in HRSC2016 are .txt files recording image names without extension.
> 
> For example:
> 
> ```
> P00001
> P00002
> ...
> ```

tnx for answering 👍 
i make them and get this error:

classname: ship
Traceback (most recent call last):
File "/content/ReDet/DOTA_devkit/hrsc2016_evaluation.py", line 307, in
main()
File "/content/ReDet/DOTA_devkit/hrsc2016_evaluation.py", line 290, in main
use_07_metric=True)
File "/content/ReDet/DOTA_devkit/hrsc2016_evaluation.py", line 179, in voc_eval
BB = BB[sorted_ind, :]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

what should i do???

**Comment by mmoghadam11** [comment]
after erasing line 179 i got this:
KeyboardInterrupt
classname: ship
check fp: []
check tp []
npos num: 1188
ap:  0.0
map: 0.0
classaps:  [0.]

**Comment by csuhan** [comment]
Please check your `.txt` result file first.

**Comment by mmoghadam11** [comment]
> Please check your `.txt` result file first.

it doesnt made

**Comment by mmoghadam11** [comment]
in 
`# generate results
!python /content/ReDet/tools/test.py /content/ReDet/configs/ReDet/ReDet_re50_refpn_3x_hrsc2016.py \
    /content/ReDet/work_dirs/ReDet_re50_refpn_3x_hrsc2016/ReDet_re50_refpn_3x_hrsc2016-d1b4bd29.pth  --out /content/ReDet/work_dirs/ReDet_re50_refpn_3x_hrsc2016/results.pkl
`
it gives `.pkl` file
after that i run this:
`# evaluation
# remeber to modify the results path in hrsc2016_evaluation.py
!python /content/ReDet/DOTA_devkit/hrsc2016_evaluation.py`
but it seems that needs `.txt` file

how can i parse `.pkl` file to `.txt` file?

**Comment by mmoghadam11** [comment]
i use tools/parse_results.py . it makes `.txt` file but still i get error:

`# evaluation remeber to modify the results path in hrsc2016_evaluation.py
!python /content/ReDet/DOTA_devkit/hrsc2016_evaluation.py`

classname: ship
Traceback (most recent call last):
  File "/content/ReDet/DOTA_devkit/hrsc2016_evaluation.py", line 307, in <module>
    main()
  File "/content/ReDet/DOTA_devkit/hrsc2016_evaluation.py", line 290, in main
    use_07_metric=True)
  File "/content/ReDet/DOTA_devkit/hrsc2016_evaluation.py", line 188, in voc_eval
    R = class_recs[image_ids[d]]
KeyError: '100000825.bmp'

**Comment by csuhan** [comment]
please manually remove the `.bmp` extension in your `.txt` result file.
We will update related code later.
